n = input('Digite algo: ')
print(type(n))
print('É alfa numerico? ', n.isalnum())
print('É alfabetico? ',n.isalpha())
print(n.isascii())
print(n.isupper())
print(n.islower())
print(n.isidentifier())
print(n.isdigit())
print(n.isspace())
